services:
  private-gpt:
    build:
      dockerfile: Dockerfile.external
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
<<<<<<< HEAD
      - 80:80
    environment:
      PORT: 80
      PGPT_PROFILES: docker
      PGPT_MODE: local

    env_file:
      - .env
    
=======
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
>>>>>>> dev
