server:
  env_name: ${APP_ENV:mistralai}

llm:
  mode: openailike

embedding:
  mode: mistralai

mistral:
  api_base: https://api.mistral.ai/v1
  api_key:
  model: mistral-large
  prompt_style: mistral
  embedding_model: mistral-embed
  request_timeout: 1000
